### ISSUE TITLE
Gif not stopping 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TimVelo/giflib#1]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?
I want the gif to be played once and then stop instead of looping again and 
again.How to do that?

What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `krishan1...@gmail.com` on 14 Jul 2014 at 1:40

**Comment by TimVelo** [comment]
If the GIF interaction on android is anything like GIF interaction in PC / web view, the animation run loop is set by the GIF file itself, not by the application. Recreate the GIF in a GIF application and disable looping in the file. I use Photoshop, and it provides this option for infinite or # of loops..
